version: '3'

services:
  # The Application
  php-challenge:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www/
    container_name: php-challenge
    volumes:
      - ./src/:/var/www/
      - ./docker/nginx/local.ini:/usr/local/etc/php/conf.d/local.ini

  # The Web Server
  web-server-challenge:
    image: nginx:1.18
    container_name: web-server-challenge
    restart: always
    depends_on:
      - php-challenge
      - composer-challenge
    volumes: 
      - ./src/:/var/www/
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
      - 443:443

  # The Database
  database-challenge:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: database-challenge
    environment:
      MYSQL_DATABASE: db_challenge
      MYSQL_USER: challenge
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    ports:
        - "3307:3306"
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql/
  
  # Composer
  composer-challenge:
    container_name: composer-challenge
    image: composer:1.8
    volumes:
      - "./src:/app"
    working_dir: "/app"
    command: composer install --ignore-platform-reqs

volumes:
  dbdata:
    driver: local

